## Configuration for github
highlighter: pygments
github: [Repository metadata]

## Configuration for Jekyll
detach: yes
name: "Eric's Blog"
description: "Eric's tech notes and life memory"
paginate: 2
markdown: rdiscount
permalink: pretty

#defaults:
#  -
#    scopes:
#      path: ""
#      type: "posts"
#    values:
#      layout: "default"
